$(function(){		
	$("#loginBtn").click(function(){
		//1、
		$.post(
			"php/logincheck.php",
			{
				"username":$("#strLoginName").val(),
				"password":$("#strPassword").val(),
			},
			function(data){	
				console.log(data);				
				if(data=="1"){//登录成功！
					//记录cookie
					saveCookie("username",$("#strLoginName").val(),7);
					location.href="index.php";
				}else{
					alert("登录失败，用户名或者密码不对！");
				}
			}
		);
	});
	$("#toRegister").click(function(){
		location.href="register.php";
	});
});